//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeritageGo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbHeritagerEntities : DbContext
    {
        public dbHeritagerEntities()
            : base("name=dbHeritagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbCommentary> tbCommentaries { get; set; }
        public virtual DbSet<tbGroup> tbGroups { get; set; }
        public virtual DbSet<tbHerinTag> tbHerinTags { get; set; }
        public virtual DbSet<tbHeritagerInfor> tbHeritagerInfors { get; set; }
        public virtual DbSet<tbHeritagerInfor_lang> tbHeritagerInfor_lang { get; set; }
        public virtual DbSet<tbImage> tbImages { get; set; }
        public virtual DbSet<tbImages_lang> tbImages_lang { get; set; }
        public virtual DbSet<tbLanguage> tbLanguages { get; set; }
        public virtual DbSet<tbLiked> tbLikeds { get; set; }
        public virtual DbSet<tbTag> tbTags { get; set; }
        public virtual DbSet<tbTag_lang> tbTag_lang { get; set; }
        public virtual DbSet<tbUserInfor> tbUserInfors { get; set; }
        public virtual DbSet<tbViewed> tbVieweds { get; set; }
    
        public virtual ObjectResult<GetCommentaryByID_Result> GetCommentaryByID(Nullable<int> iD, Nullable<int> nums, Nullable<int> nume)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var numsParameter = nums.HasValue ?
                new ObjectParameter("nums", nums) :
                new ObjectParameter("nums", typeof(int));
    
            var numeParameter = nume.HasValue ?
                new ObjectParameter("nume", nume) :
                new ObjectParameter("nume", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCommentaryByID_Result>("GetCommentaryByID", iDParameter, numsParameter, numeParameter);
        }
    }
}
