//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeritageGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHeritagerInfor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbHeritagerInfor()
        {
            this.tbCommentaries = new HashSet<tbCommentary>();
            this.tbHerinTags = new HashSet<tbHerinTag>();
            this.tbImages = new HashSet<tbImage>();
            this.tbLikeds = new HashSet<tbLiked>();
            this.tbVieweds = new HashSet<tbViewed>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string TimeofBuild { get; set; }
        public string Address { get; set; }
        public string Contents { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public System.Data.Entity.Spatial.DbGeography Location { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCommentary> tbCommentaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbHerinTag> tbHerinTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbImage> tbImages { get; set; }
        public virtual tbHeritagerInfor_lang tbHeritagerInfor_lang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLiked> tbLikeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbViewed> tbVieweds { get; set; }
    }
}
